- jcloud/auth.py
This prevents automatic login and does not ask the user to login again after the user completes his/her login in the browser for the first time.
> fix(auth): always requires login from auth0

- jcloud/__main__.py
- jcloud/constants.py
- jcloud/flow.py
- jcloud/parsers/list.py
- Set the default loglevel to `INFO`.
- Removed debug logging from `asyncio`, i.e., the logs start with `Using selector..`.
- Streamed logs from WOLF now won't print if the log level is above `DEBUG`.
- fixed `--loglevel` option; the CLI wasn't respecting the input, because in `get_main_parser`, the `get_logger` was first imported by `set_list_parser`, which was **before** we set `os.environ['JCLOUD_LOGLEVEL']` in `__main__.py`, which means the input not respected. I introduced a new module `constants.py` so the `get_logger` will only be imported after the env set.
Here are new UX (`INFO` being the default, but with `--loglevel DEBUG` we get to see more):
> Log level fixes/updates

- jcloud/api.py
Currently `jc status` doesn't handle errors from wolf gracefully, i.e., the unexpected errors causing `_result` to be `None`:
This PR improved it by taking care of the `None`, the message is open to change:
> refactor: handle errors from jc status more gracefully

- jcloud/flow.py
Fixes #35 
Without name:
With name:
> fix: show name in deploy message

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/integration-tests.yml
**Goal**
This is to fix the situation where debug logs aren't printed in CI/CD.
Ref: https://stackoverflow.com/questions/4673373/logging-within-pytest-tests.
Test new run after applying this fix:
https://github.com/jina-ai/jcloud/runs/6649703435?check_suite_focus=true.
As you can see the debug loggings were also printed.
> ci: make log level to be DEBUG when running pytest in ci/cd

- tests/integration/test_executors_from_external_sources.py
**Goal**
This test is currently not reliable due to https://github.com/jina-ai/jcloud/issues/45.
> test: skip test_executors_from_external_sources for now

- tests/integration/test_executors_from_external_sources.py
**Goal**
Now that [this issue](https://github.com/jina-ai/jcloud/issues/45) is fixed, let's undo the test skip.
Link: https://github.com/jina-ai/jcloud/actions/runs/2445866771
> test: undo external source integration test skip

- .github/workflows/cd.yml
**Goal**
Attempt to fix issue https://github.com/jina-ai/jcloud/issues/51.
Integration tests won't apply here.
> ci: add auth to cd workflow

- jcloud/flow.py
**Goal**
This is for https://github.com/jina-ai/wolf/issues/143.
When token is expired, it returns `HTTPStatus.FORBIDDEN`, we should capture that and show it to user.
Integration tests: https://github.com/jina-ai/jcloud/actions/runs/2472532350
> fix: when token is expired, prompt should show

- README.md
- tests/integration/flows/expose-version-arg.yml
- tests/integration/test_expose_version_arg.py
**Goal**
A part of https://github.com/jina-ai/wolf/issues/117, we need to make sure e2e tests starting from client side cover the new feature as well. 
> test: add integration test to cover wolf's jina version support

- jcloud/api.py
- jcloud/env_helper.py
- jcloud/flow.py
- jcloud/helper.py
- setup.py
**Goal**
- Previously for `expose_gateway=False` flows, the parsing was incorrect in list view.
ref:  https://jinaai.slack.com/archives/C03F1BG5VMW/p1655087874560469
```
File "/Users/zacli/Code/jcloud/jcloud/api.py", line 109, in list
await _list_by_status(args.status)
File "/Users/zacli/Code/jcloud/jcloud/api.py", line 101, in _list_by_status
cleanup(k['ctime']),
File "/Users/zacli/Code/jcloud/37_env/lib/python3.7/site-packages/rich-12.4.4-py3.7.egg/rich/table.py", line 461, in add_row
f"unable to render {type(renderable).__name__}; a string or other renderable object is required"
rich.errors.NotRenderableError: unable to render dict; a string or other renderable object is required
```
- Added `packaging` dependency and removed `jina` dependency in `env_helper` so that we don't have …
> fix: list render, jcloud dependencies and jcloud logging

- jcloud/flow.py
- jcloud/helper.py
- tests/unit/test_helper.py
Extra handle for 'dashboards' key; the value is a map but since we only have monitoring dashboard at the moment,
for simplicity we turn the map to a string for display purpose.
Now for Flow that has have monitoring turned on:
Flow that doesn't have monitoring turned on (`dashboards` would be hidden):
Additional I also added logic to make sure we don't show `endpoints` and `gateway` at the same way which might confuses user.
> feat: add handle for displaying dashboards in jc status

- jcloud/helper.py
- tests/integration/flows/executors-autoscaled.yml
- tests/integration/test_executors_autoscaled.py
To make `jinahub+serverless` protocol work, we need to accept it in `jc` (`CloudFlow`), otherwise it would think it's not a valid URL and make the deployment go to normalization route instead.
I'm also adding integration test to cover knative case.
Integration tests (passed): https://github.com/jina-ai/jcloud/actions/runs/2829973362
> feat: add knative support and test

- jcloud/__main__.py
- jcloud/parsers/__init__.py
- jcloud/parsers/base.py
**Goal**
- Should allow jina to extend its own CLI with jcloud cli
> feat: allow extending cli parser with jcloud cli

- jcloud/api.py
- jcloud/flow.py
- jcloud/helper.py
- tests/integration/flows/executors-autoscaled.yml
- tests/unit/test_helper.py
2nd attempt after #73 
Previously the tests were broken because changes in `prepare_flow_model_for_render`  breaks `_fetch_until` , as it invokes `prepare_flow_model_for_render` during `self.status`. And before the deployment is done, `dashboards` key is not in `response`.
This PR moves `prepare_flow_model_for_render` to `api.status` to avoid it (`_fetch_until` doesn't need to `prepare_flow_model_for_render` anyway, the latter is only for formatting the JSON result to be ready for UI rendering )
Tests (passed):  https://github.com/jina-ai/jcloud/actions/runs/2916228663
> feat: changes to accommodate the monitoring changes

- jcloud/flow.py
**Goal**
We need to show the actual message if a user reaches the max Flows allowed otherwise it's misleading
> fix: surface the max flow allowed error

- jcloud/flow.py
- jcloud/helper.py
**Goal**
Pointing the user to the Flow deployment logs panel directly
> refactor: show flow deployment logs url

- jcloud/helper.py
- tests/unit/flows/normalized_flows/flow2.yml
**Goal**
serverless support was removed by https://github.com/jina-ai/jcloud/pull/103/files.
This syntax is something that's specific to us not Hubble, so we need to handle that in addition to what Hubble has been already doing. Otherwise we would have validation error.
I verified that it's now working locally after the patch.
> fix: handle the validation for serverless

- jcloud/normalize.py
- tests/unit/test_normalize.py
**Goal**
resolve the bug when the output argument of  is a file. `jc normalize -o foo.yml flow.yml` will output to
`foo.yml/flow.yml`.
> fix: fix the bug when output argument is a file

- .github/workflows/integration-tests.yml
- jcloud/api.py
- jcloud/flow.py
- jcloud/normalize.py
- jcloud/parsers/list.py
- jcloud/parsers/remove.py
**Goal**
Fixes https://github.com/jina-ai/jina-operator/issues/279
Changes the behaviour of:
* `jc list` where if no value is passed all flows that are in `Serving` or `Failed` phase are listed
* `jc remove` where if `all` is passed all flows that are in `Serving` or `Failed` phase are deleted
`jc list`
`jc remove`
Flows are removed
> fix: list & remove serving & failed flows

- .github/workflows/integration-tests.yml
- jcloud/api.py
**Goal**
`jc list` only shows `Serving` & `Failed` Flows, unlike JAC which shows all Flows except `Deleted` ones.
> fix(list): change default phases in jc list

- jcloud/api.py
- jcloud/flow.py
- tests/integration/remove_multiple/test_multi_flows_removal.py
- tests/unit/test_api.py
**Goal**
Attempts to fix issue with this [test](https://github.com/jina-ai/jcloud/actions/runs/4475421846/jobs/7864828339).
It adds the phase as an optional parameter to `_terminate_flow_simplified()` to avoid failing on intermediate flow status checks.
> fix: add phase to intermediate phases

- jcloud/api.py
- jcloud/flow.py
- jcloud/parsers/list.py
**Goal**
Adds support to list flows by labels.
Three flows are submitted with 2 flows sharing the same labels
Listing flows with `username=npitsillos` returns all flows
Listing flows with `username=npitsillos,app=test-app`
> feat: add labels to list

- jcloud/flow.py
- tests/integration/normalized_flow_env_vars/flow.yml
- tests/integration/normalized_flow_env_vars/test_normalized_flow_env_vars.py
- tests/integration/update/test_update_executor_args.py
**Goal**
- Closes #141 
```yaml
jtype: Flow
with:
protocol: http
name: test-flow
env:
TEST_ENV_VAR: ${{ ENV.VAR }}
executors:
- uses: jinaai+docker://auth0-unified-64c3e19b1d2f398f/JCloudCISentencizer:latest
```
Deploying flow with `env` var in environment
> fix: adding env vars for normalized flows

- jcloud/flow.py
- jcloud/normalize.py
- tests/unit/flows/flow-with-labels.yml
- tests/unit/flows/flow-with-obj-label.yml
- tests/unit/test_normalize.py
**Goal**
- Parses the flow dict loaded with `JAML.load` and converts the change types of `jcloud.labels` from an `int` to `str`
> fix: parse jcloud labels as str

- jcloud/flow.py
- tests/integration/validate/flows/invalid-flow.yml
- tests/integration/validate/flows/valid-flow.yml
- tests/integration/validate/test_validate.py
**Goal**
- Closes [jina-ai/jina-operator#396](https://github.com/jina-ai/jina-operator/issues/396)
For the below `flow.yml`
```yml
jtype: Flow
gateway:
protocol: http
executors:
- name: sentencizer
uses: jinahub+docker://Sentencizer
jcloud:
monitor:
traces:
host: 123
```
The output of `jc deploy flow.yml` is the following
> feat: check flow is valid before deployment

- .github/workflows/integration-tests.yml
- jcloud/helper.py
- jcloud/normalize.py
- tests/integration/test_jina_new.py
- tests/unit/test_helper.py
- tests/unit/test_normalize.py
> fix: set docarray version on load flow data
