jcloud/__init__.py
jcloud/api.py
jcloud/auth.py
jcloud/flow.py
jcloud/parsers/__init__.py

Ref https://github.com/jina-ai/hubble/issues/354

feat(auth): `jcloud login` cli

---

jcloud/env_helper.py
jcloud/flow.py
jcloud/helper.py
tests/unit/flows/normalized/flow8.yml
tests/unit/flows/normalized/flow9.yml
tests/unit/flows/not/flow4.yml
tests/unit/test_helper.py

Explained in https://github.com/jina-ai/wolf/issues/94

feat: normalized function now will try to merge envs before validation

---

jcloud/flow.py
tests/unit/test_flow.py

Now all the path/env_file related checks are moved to `__post_init__ `

feat: validate CloudFlow's path and env_file during post init

---

jcloud/helper.py

This is to update the dependency so we don't have below warnings:
Some refs:
https://github.com/jina-ai/auth/blob/main/auth/helper.py
https://github.com/jina-ai/jina/pull/4362

refactor: replace distuils with packaging

---

.github/workflows/ci.yml
tests/unit/test_flow.py

test: fix setup for running test in ci/cd

---

README.md

[Preview](https://github.com/jina-ai/jcloud/blob/remove-doc/README.md)

doc: doc for jc remove

---

README.md
tests/integration/capacity/flows/capacity.yml
tests/integration/capacity/test_capacity.py

feat: spot vs ondemand for executors

---

jcloud/flow.py
tests/integration/capacity/test_capacity.py
tests/unit/test_api.py
tests/unit/test_helper.py

chore: show error message from server

---

jcloud/flow.py

We are sometimes seeing `ClientConnectionError` from Wolf API:
https://jinaai.slack.com/archives/C03434J5BND/p1657567326058929
So in this PR I propose adding a retry after 2s sleep to start with. 
Ran the CLI locally; it's working as expected.

feat: add retry in _deploy

---

tests/integration/flows/resource-demand.yml
tests/integration/test_customized_resources.py

test: add integration test to cover customized resources

---

setup.py
tests/integration/flows/resource-demand.yml

chore: update jina version in tests and fix test fixtures

---

tests/integration/flows/executors-autoscaled.yml
tests/integration/flows/resource-in-gateway.yml
tests/integration/test_gateway_resource_customization.py

Tests: https://github.com/jina-ai/jcloud/actions/runs/2859403100

test: add test coverage for gateway resource customization

---

jcloud/helper.py
tests/integration/flows/executors-autoscaled.yml
tests/unit/test_helper.py

Changes on `jc` side for https://github.com/jina-ai/wolf/pull/309

feat: changes to accommodate the monitoring changes

---

jcloud/helper.py
tests/integration/flows/executors-autoscaled.yml
tests/unit/test_helper.py

jina-ai/jcloud#73 breaks all [integration tests](https://github.com/jina-ai/jcloud/actions/runs/2913017971). Reverting.

Revert "feat: changes to accommodate the monitoring changes"

---

tests/integration/test_jina_new.py

test: add integration test for jina new project (#76)

---

jcloud/api.py

**Goal**
I'm also leaving the streaming code for now just in case.

feat: dashboard url display in jc logs

---

jcloud/flow.py

feat: dashboard url display in jc deploy

---

tests/integration/flows/executors-from-external-sources.yml

test: fix external sources executor test's workspace to the same one

---

jcloud/constants.py

**Goal**
@jina-ai/team-wolf 
Tests passed: https://github.com/jina-ai/jcloud/actions/runs/3110789454

fix: hubble URL update

---

.github/workflows/integration-tests.yml
jcloud/constants.py

chore: change default host

---

jcloud/constants.py

refactor: remove unused code

---

jcloud/flow.py
jcloud/helper.py

**Goal**
Add dashboard link to redirect users to Flow deployment logs

feat(deploy): log dashboard link

---

jcloud/api.py
tests/unit/test_api.py

**Goal**
Fix issues with `jc remove all`

fix(remove): jc remove all

---

jcloud/api.py

Fixes: https://github.com/jina-ai/hub-website/issues/381
Shouldn't touch any logic inside wolf, so I won't run the integration test for now. 
**Goal**

fix: use new login each time intead of reusing cached credential

---

.github/workflows/ci.yml

ci: remove codecov job

---

jcloud/normalize.py

**Goal**
Fixes an issue where `jcloud` reads the default `flow.yml` when multiple flow files exists in the project directory.
Fixes temporary file naming.

fix: reading correct file when multiple flow files in dir

---

jcloud/constants.py
jcloud/flow.py
jcloud/helper.py
jcloud/normalize.py
tests/integration/expose/flows/single-executor-stateful.yml
tests/integration/expose/flows/single-executor-stateless.yml
tests/unit/test_flow.py

chore: fix expose test

---

jcloud/api.py
jcloud/helper.py
setup.py

**Goal**
Changes the flow's creation times to show local timezone time with GMT offset.
Closes #98 

fix: show timezone offset

---

tests/integration/test_jina_new.py

chore: skip jina new test

---

jcloud/api.py
jcloud/flow.py
jcloud/helper.py
jcloud/parsers/__init__.py
jcloud/parsers/update.py
tests/integration/update/flows/add_args.yml
tests/integration/update/flows/add_env.yml
tests/integration/update/flows/add_labels.yml
tests/integration/update/flows/base_flow.yml
tests/integration/update/flows/custom_name_executor.yml
tests/integration/update/flows/custom_name_exposed_executor.yml
tests/integration/update/flows/expose_executor.yml
tests/integration/update/flows/modify_delete_labels.yml
tests/integration/update/flows/modify_env.yml
tests/integration/update/flows/scale_out.yml
tests/integration/update/flows/update_image.yml
tests/integration/update/flows/update_resources.yml
tests/integration/update/test_rename_executor.py
tests/integration/update/test_update_env.py
tests/integration/update/test_update_executor_args.py
tests/integration/update/test_update_executor_image.py
tests/integration/update/test_update_executor_resources.py
tests/integration/update/test_update_expose_executor.py
tests/integration/update/test_update_labels.py
tests/unit/test_api.py

**Goal**
>  `jc update <flow> <path/to/flow/file>`

feat(cli): update flow

---

jcloud/api.py
jcloud/constants.py
jcloud/flow.py
jcloud/helper.py
jcloud/parsers/__init__.py
jcloud/parsers/custom_actions.py
tests/integration/cutom_actions/flows/base_flow.yml
tests/integration/cutom_actions/test_restart.py
tests/unit/test_api.py

feat: restart flow, executor or gateway

---

jcloud/api.py
jcloud/constants.py
jcloud/flow.py
jcloud/parsers/__init__.py
jcloud/parsers/custom_actions.py
tests/integration/cutom_actions/test_pause_resume.py
tests/unit/test_api.py

feat: flow pause / resume

---

jcloud/api.py
jcloud/constants.py
jcloud/flow.py
jcloud/parsers/__init__.py
jcloud/parsers/custom_actions.py
tests/integration/cutom_actions/test_scale.py
tests/unit/test_api.py

**Goal**
This PR adds functionality to scale an executor of a Flow. 

feat: `jc scale`

---

jcloud/helper.py
jcloud/normalize.py
tests/integration/executor_uses/flow.yml
tests/integration/executor_uses/test_executor_uses.py

fix: update uses on legacy syntax

---

jcloud/api.py
jcloud/normalize.py
jcloud/parsers/normalize.py
tests/unit/test_normalize.py

feat: add output argument to jcloud normalize

---

jcloud/parsers/custom_actions.py

fix: jc scale wording

---

.github/workflows/integration-tests.yml
jcloud/api.py
jcloud/parsers/__init__.py
jcloud/parsers/remove.py
tests/integration/remove_by_phase/test_remove_by_phase.py
tests/unit/test_api.py

**Goal**
Enables deletion of all flows matching the passed phase
Closes [jina-ai/jina-operator#338](https://github.com/jina-ai/jina-operator/issues/338)
**remove before**
**remove after**
**remove Usage**

feat: remove flows by phase

---

jcloud/flow.py
jcloud/helper.py

**Goal**
- [Attempt 1](https://github.com/jina-ai/jcloud/actions/runs/4364440747/attempts/1) :heavy_check_mark: 
- [Attempt 2](https://github.com/jina-ai/jcloud/actions/runs/4364440747/attempts/2) :heavy_check_mark: 
- [Attempt 3](https://github.com/jina-ai/jcloud/actions/runs/4364440747/) :heavy_check_mark: 

fix: limit aiohttp connections

---

tests/integration/remove_by_phase/test_remove_by_phase.py

**Goal**
Adds more tests for `jc recreate` and renames the `custom_actions` folder to fix a typo.

test: remove by phase integration tests

---

jcloud/api.py
jcloud/flow.py
jcloud/helper.py

**Goal**
Fixes: https://github.com/jina-ai/jina-operator/issues/388
After:

feat: add cph display

---

jcloud/flow.py

chore: skip flow deployment message

---

jcloud/flow.py

fix: fix retry flow deployment

---

jcloud/api.py
jcloud/constants.py
jcloud/flow.py
jcloud/helper.py
jcloud/normalize.py

**Goal**
Change all `dashboard.wolf.jina.ai` links to `cloud.jina.ai` links
**jc status**
**jc deploy**

refactor: change dashboard urls to cloud.jina.ai

---

jcloud/flow.py

feat: hide ui for lcserve resume pause

---

jcloud/api.py
jcloud/flow.py
jcloud/parsers/__init__.py
jcloud/parsers/deploy.py
jcloud/parsers/normalize.py

**Goal**
- Closes #163 
`jc jobs list/get`

Refactor cli

---

jcloud/api.py
tests/unit/flows/flow1-test.yml
tests/unit/test_api.py

refactor: display resources

---

jcloud/api.py
jcloud/flow.py
jcloud/parsers/create.py
tests/integration/jobs/test_jobs.py
tests/unit/test_api.py

chore: entrypoint accepts multiple args as list

---

jcloud/api.py

Update job create
